name: options-backtest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyterlab
  - yfinance
  - requests
  - beautifulsoup4
  - numba
  - scikit-learn
  - statsmodels
  - ta-lib
  - quantlib
  - pip
  - pip:
    - py_vollib
    - mibian
    - backtrader
    - vectorbt
    - empyrical
    - pandas_ta
    - mplfinance
    - yahooquery
    - ipykernel
